### ISSUE TITLE
On 'composer install', package is not being installed in vendor directory

### ISSUE THREAD

**Issue by fuhton** [eugene-manuilov/wp-codeception#13]
On 'composer install', the package is creating a new series of directories in the current directory, **DIR** -> wp-content -> plugins -> wp-codeception, instead of being placed in the vendor directory.

Is this the expected functionality?

**Comment by eugene-manuilov** [comment]
It happens because you use `composer/installers` in you project. That package installs dependencies into different folders based on dependency type. `wp-codeception` plugin has `wordpress-plugin` type, that is why installer installs it into `/wp-content/plugins/{$name}` folder. So it is expected behavior and can't be considered as a bug.

What you need to do is to update your `composer.json` file to install `wordpress-plugin` dependencies into `vendor` folder. It could be done easily by adding following snippet:

```
{
    ...,
    "extra": {
        "installer-paths": {
            "vendor/{$name}/": ["type:wordpress-plugin"]
        }
    },
    ...
}
```

Also you need to update your `autoload` section and add `wp-codeception.php` file to the files list:

```
{
    ...,
    "autoload": {
        "psr-X": {
            ...
        },
        "files": [
            ...,
            "vendor/wp-codeception/wp-codeception.php"
        ]
    },
    ...
}
```

**Comment by fuhton** [comment]
Awesome. Thanks for the overview. Didn't know about composer type declaration.
